Finish very basic instruction for network mode installation
chainstack/graph-deployment pull request #61
Opened 2021-09-01 21:10 UTC by dm3ch

/closes https://github.com/chainstack/graph-deployment/issues/15

2021-09-02 05:34 UTC, CaJIbHuK requested changes

2021-09-02 05:34 UTC, CaJIbHuK commented on helmfile/README.md
> +This The Graph doc could be useful - https://thegraph.com/docs/indexing .
```suggestion
More information about indexing could be found [here](https://thegraph.com/docs/indexing).
```

2021-09-02 05:34 UTC, CaJIbHuK commented on helmfile/README.md
> +1. Blank network providers found in `values/graphprotocol-node*` in `config.chains`, if the network wasn't configure don't remember to comment it out.
Tbh, didn't fully understand what you meant here. Maybe the following line describes what you want to say:

```suggestion
Don't forget to fill in the `config.chains` value in the `values/graphprotocol-node*` file.
```
+
maybe `Some possible errors could be` line can be removed.

2021-09-02 05:34 UTC, CaJIbHuK commented on helmfile/README.md
> +https://thegraph.com/docs/indexing#from-npm-packages
```suggestion
Please, install graph-cli and indexer-cli according to the following [guide](https://thegraph.com/docs/indexing#from-npm-packages).
```

2021-09-02 05:34 UTC, CaJIbHuK commented on helmfile/README.md
> +First you need to run port-forward command:
```suggestion
First, you need to run the port-forward command:
```

2021-09-02 05:34 UTC, CaJIbHuK commented on helmfile/README.md
> +Connect cli:
```suggestion
Then, connect with graph-cli and check status:
```

2021-09-02 05:34 UTC, CaJIbHuK commented on helmfile/README.md
> +graph indexer status
```suggestion
graph indexer connect http://localhost:18000
graph indexer status
```

2021-09-02 05:34 UTC, CaJIbHuK commented on helmfile/README.md
> +Other useful commands for subgraphs and cost model configuration could be found there: https://thegraph.com/docs/indexing#usage-1
```suggestion
Other useful commands for subgraphs and cost model configuration could be found [here](https://thegraph.com/docs/indexing#usage-1).
```

2021-09-03 07:38 UTC, CaJIbHuK approved these changes

2021-09-03 07:38 UTC, CaJIbHuK commented
@akegaviar please look through

2021-09-03 07:39 UTC, akegaviar approved these changes

2021-09-03 08:53 UTC, merged