Fix connection to postgres from grafana
chainstack/graph-deployment pull request #72
Opened 2021-09-06 21:47 UTC by dm3ch

/close https://github.com/chainstack/graph-deployment/issues/58

2021-09-07 16:08 UTC, CaJIbHuK requested changes
@akegaviar please review

2021-09-07 16:08 UTC, CaJIbHuK commented on helmfile/INFRA_README.md
> +Some of dashboards was inspired or based on https://github.com/StakeSquid/graphprotocol-mainnet-docker/tree/advanced/grafana/provisioning/dashboards
```suggestion
Some of the dashboards were inspired or based on https://github.com/StakeSquid/graphprotocol-mainnet-docker/tree/advanced/grafana/provisioning/dashboards.
```

2021-09-07 16:08 UTC, CaJIbHuK commented on helmfile/INFRA_README.md
> +In order to make dashboards that uses postgres data work you should pass postgres password to values after graph installation and reapply infra helmfile.
```suggestion
In order to make the dashboards that uses postgres data work you have to pass postgres password to values after graph installation and reapply infra helmfile.
```

2021-09-07 16:08 UTC, CaJIbHuK commented on helmfile/INFRA_README.md
> +You should pass it to `postgresDatasource.password` field in `infra.secret.yaml` and run appli command again.
```suggestion
You have to pass it to `postgresDatasource.password` field in `infra.secret.yaml` and run `apply` command again.
```

2021-09-07 16:08 UTC, CaJIbHuK commented on helmfile/INFRA_README.md
> +After that you should restart grafana pod to make changes take effect.
```suggestion
After that, restart grafana pod to make changes take effect.
```

2021-09-08 00:41 UTC, akegaviar approved these changes

2021-09-08 06:12 UTC, CaJIbHuK approved these changes

2021-09-08 06:12 UTC, merged